In [1]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero.
import numpy as np
x = np.array([1, 0, 0, 0])
print(np.any(x))
x = np.array([0, 0, 0, 0])
print(np.any(x))

True
False


In [2]:
#Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
#Expected Output:Original array:[[ 0 1 2 3 4 5] [ 6 7 8 9 10 11]]
#Difference between the maximum and the minimum values of the said array:[5 5]
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print("\nDifference between the maximum and the minimum values of the array:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Difference between the maximum and the minimum values of the array:
[5 5]


In [3]:
#Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
#Expected Output:
#Original array:[1.0, 2.0, 3.0, 4.0]
#Largest integer smaller or equal to the division of the inputs:
# [ 0. 1. 2. 2.]
import numpy as np
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]


In [4]:
#Write a NumPy program to compute the median of flattened given array. 
# Note: First array elements raised to powers from second array
#Expected Output:Original array:[[ 0 1 2 3 4 5][ 6 7 8 9 10 11]]
#Median of said array:5.5
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Median of said array:
5.5


In [5]:
#Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.
#Sample output:Original array:[0 1 2 3 4 5]
#Mean: 2.5
# std: 1
# variance: 2.9166666666666665
import numpy as np
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)


Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


In [6]:
#Write a NumPy program to compute the weighted average of a given array.
#Sample Output:Original array:[0 1 2 3 4]
#Weighted average of the said array:2.6666666666666665
import numpy as np
x = np.arange(5)
print("\nOriginal array:")
print(x)
weights = np.arange(1, 6)
r1 = np.average(x, weights=weights)
r2 = (x*(weights/weights.sum())).sum()
assert np.allclose(r1, r2)
print("\nWeighted average of the said array:")
print(r1)


Original array:
[0 1 2 3 4]

Weighted average of the said array:
2.6666666666666665


In [7]:
#Write a NumPy program to compute the covariance matrix of two given arrays.
#Sample Output:Original array1:[0 1 2] Original array1:[2 1 0]
#Covariance matrix of the said arrays:[[ 1. -1.] [-1. 1.]]
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


In [9]:
# Write a NumPy program to compute cross-correlation of two given arrays.
#Sample Output:Original array1:[0 1 3] Original array1:[2 4 5]
#Cross-correlation of the said arrays:[[2.33333333 2.16666667] [2.16666667 2.33333333]]
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 3]

Original array1:
[2 4 5]

Cross-correlation of the said arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


In [10]:
#Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.
#Sample Output:Original array1:[0 1 3] Original array1:[2 4 5]
#Pearson product-moment correlation coefficients of the said arrays:[[1. 0.92857143]
# [0.92857143 1. ]]
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nPearson product-moment correlation coefficients of the said arrays:\n",np.corrcoef(x, y))


Original array1:
[0 1 3]

Original array1:
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


In [11]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays. 
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [12]:
# Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [13]:
# Write a NumPy program to test whether none of the elements of a given array is zero.
import numpy as np
x = np.array([1, 2, 3, 4])
print(np.all(x))


x = np.array([0, 1, 2, 3])
print(np.all(x))

True
False


In [14]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 
import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


In [15]:
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
# Write a NumPy program to test element-wise for positive or negative infinity.
import numpy as np, math
a = np.array([1, 0,math.inf, -math.inf, float('inf'), float('-inf')])
print(np.isinf(a))

[False False  True  True  True  True]
